### ISSUE TITLE
How do you obtain the data from row data, such as ICEWS18?

### ISSUE THREAD

**Issue by sirius-aerostar** [INK-USC/RE-Net#11]
I want to know what is the meaning of the numbers (entities and relations) in the train/test data. How can I know the relationship between the entity name and the number?

**Comment by woojeongjin** [comment]
We first got the raw datasets as described in the README.md.
Then we sort the dataset by time in the increasing order and delete duplicate quadruples.
The numbers are assigned randomly where each number corresponds to each entity or relation.

**Comment by sirius-aerostar** [comment]
Thank you for your reply!  Is it possible to provide the entity to number mapping file?

**Comment by shanzhenren** [comment]
@sirius-aerostar Thanks! We will upload the mapping files soon @woojeongjin
