### ISSUE TITLE
How to train without GPU

### ISSUE THREAD

**Issue by MartinZZZ** [INK-USC/RE-Net#13]
As we only have multi-core CPUs available currently, can we train without GPUs?

**Comment by woojeongjin** [comment]
In the current code, no.
But you can run without GPU by changing all GPU tensors to CPU tensors.

Thanks!

**Comment by shanzhenren** [comment]
Hi @MartinZZZ, @woojeongjin will push an update on the script with CPU training option, even though we highly recommend to do GPU training for efficiency consideration.
