### ISSUE TITLE
entity2id, relation2id

### ISSUE THREAD

**Issue by JiajunBao** [INK-USC/RE-Net#16]
Where can I get the mapping from ids to entities, or ids to relations for the datasets? Thank you.

**Comment by woojeongjin** [comment]
I uploaded mapping files!
Thanks!

**Comment by JiajunBao** [comment]
Thanks!

—
Best regards,
Jiajun Bao 鲍家君
Computer Science in Engineering, University of Michigan
Phone: 734.263.8657 | Email: jiajunb@umich.edu

2019年8月25日 -0400 AM12:22 Woojeong Jin <notifications@github.com>，写道：

**Comment by sushant21** [comment]
Hi,
Can you upload the WIKI/YAGO mapping files as well?
