### ISSUE TITLE
The dataset statistic in paper is inconsistent with the data file.

### ISSUE THREAD

**Issue by Lee-zix** [INK-USC/RE-Net#17]
Table 1 in your paper shows that the test set of ICEWS18 has 69,514 triples, while the test file  you upload https://github.com/INK-USC/RE-Net/blob/master/data/ICEWS18/test.txt  has only 49545 triples. And the entity num is 23,034 in your upload file, while the number in your paper is 23,033.  Is the statistic in paper wrong? Or you upload the wrong test file??

**Comment by woojeongjin** [comment]
The test set has 49545 triples. It is a typo in the paper. 
Entity num is 23,033.
Thanks!
