### ISSUE TITLE
Can you please provide all the packages with their versions?

### ISSUE THREAD

**Issue by ngl567** [INK-USC/RE-Net#27]
Thank you for your excellent research and open source codes. But I cannot run your codes, I hope you can provide all the names of packages with their versions required for running codes. Thank you very much.

**Comment by ngl567** [comment]
Can you please provide a requirements.txt for installing all the packages to run the codes.

**Comment by woojeongjin** [comment]
Hi I have updated README.md with the installation commands. 
If you have further questions please send an email to woojeong.jin@usc.edu!
Thanks!
