### ISSUE TITLE
What is the full name of MLP in the paper? Thanks!

### ISSUE THREAD

**Issue by chuhang123** [INK-USC/RE-Net#31]

**Comment by woojeongjin** [comment]
Hi, 
It is called "Multilayer Perceptron."

Thanks for your interest!

**Comment by chuhang123** [comment]
@woojeongjin   Thank you very much for your answer. Could you answer my other question? [issue32](https://github.com/INK-USC/RE-Net/issues/32) I really need the YAGO and WIKI datasets for comparative experiments. Thanks again.
