### ISSUE TITLE
the time for training

### ISSUE THREAD

**Issue by Yongquan-He** [INK-USC/RE-Net#38]
hello!
I am interested in your excellent work!
But when I run your code, I notice that the training process is time consuming.
So I want to know how much time per epoch need in each data set!
Thanks!

**Comment by fangyiming** [comment]
> hello!
> I am interested in your excellent work!
> But when I run your code, I notice that the training process is time consuming.
> So I want to know how much time per epoch need in each data set!
> Thanks!
HELLO,I'm checking too.Can you run his code? Or could you please send your code to me? Thank you, my email is1043630181@qq.com

**Comment by woojeongjin** [comment]
Hello!

1 epoch takes about 1500 seconds = 25 mins on ICEWS18.
Bigger datasets will take more time!

Thanks for your interest!

**Comment by fangyiming** [comment]
Thank you very much for your reply. I have been studying the temporal knowledge map recently and read your paper. I am very interested. But when I want to run the code, I encounter many problems. It is my configuration problem. If you can send me the complete code, I would like to thank you very much.


---Original---

**Comment by woojeongjin** [comment]
Hi @fangyiming 
The repo includes the complete code.
I have updated the instruction for installation.
If the instruction doesn't work, could you open a new issue and describe your error messages?
