### ISSUE TITLE
Relation names for GDELT

### ISSUE THREAD

**Issue by yiskax** [INK-USC/RE-Net#39]
I'm interested in your work, and appreciate your effort of making the datasets public so much!

Could you please provide the relation names of GDELT (the rel2id file only contains numbers), and entity2id & rel2id files for WIKI and YAGO? Thanks a lot!

**Comment by woojeongjin** [comment]
Hello!

You could find relation names of GDELT in this [link](https://www.gdeltproject.org/data/documentation/CAMEO.Manual.1.1b3.pdf). 
The number corresponds to CAMEO code.

**Comment by yiskax** [comment]
Thanks！
