### ISSUE TITLE
Can this project work with CPU?

### ISSUE THREAD

**Issue by mscsedu** [INK-USC/RE-Net#44]
As the title, can this project work with CPU as I don't have GPU. Moreover, what will be the estimated performance?

**Comment by mscsedu** [comment]
Secondly, For TATransE, there are no files created during the data preprocessing of data named train2id.txt, valid2id.txt, test2id.txt. These files are called in TATransE in line 142. Could you please guide me about these files? Or they simply the train, test, and valid file?

**Comment by woojeongjin** [comment]
Unfortunately, the code does not work with CPU.

For TATransE, you should run the following commands
`cd data
python3 preprocess_TA_step1.py ICEWS18
python3 preprocess_TA_step2.py ICEWS18`

**Comment by CaiWZ** [comment]
can you tell me the version of dgl. when I run codes .
` Cannot assign node feature "h" on device cuda:0 to a graph on device cpu. Call DGLGraph.to() to copy the graph to the same device.`. I don't know how to fix it.
