### ISSUE TITLE
metric,know-evolve and WIKI datasets question

### ISSUE THREAD

**Issue by CaiWZ** [INK-USC/RE-Net#48]
Hi, Gentleman

   Thank you for your excellent research and open source codes about RE-Net, I have some questions about this paper. 
     1. But I can run codes in ICEWS14 and ICEWS18 in pretrain.py，But CUDA out of memory in WIKI even though the batch is 16, I don't how can I update codes. my pytorch is 1.7 python is 3.7.9 dgl is  '0.4.3post2',CUDA Version: 11.0
     2.  ICEWS14 does not have vaild.txt, so how can i run it?
     3. In Metric, I think only fifilter from the list all the events that occur on [time] maybe is a good idea?   

![image](https://user-images.githubusercontent.com/33720730/136641224-11ddd439-fd6f-4d3a-b824-ed1bfb0c622d.png)

       

     4. If you implement Know-Evolve in pytorch, can you provide codes.

   Thanks a lot!

**Comment by woojeongjin** [comment]
Hi!
1. Did you try a smaller batch size? 
2. I used the last checkpoint to test in ICEWS14. 
3. Yes you could filter all the events on [time]. But in my implementation, I didn't do that.
4. I used the official Know-evolve.

Thanks!
