### ISSUE TITLE
some questions regarding entity id

### ISSUE THREAD

**Issue by dnanad** [INK-USC/RE-Net#49]
Hello, I have some questions regarding, how to assign ids to the entities. 

I am assuming that the entity ids that you have added are for all the subject and object entities together. 
I have few question wrt to WIKI and YAGO data:

1. Is there any fix rule/method how you assign the ids, especially for WIKI data?
2. Does enumerating all the unique entities and assigning corresponding number make sense?
3. Will there be any ambiguity if for the subject and object entities, ids are being independently assigned? For example, certain entity which appears as subject as well as object might have different ids. 
4. Why do we need a time period for the entities in YAGO data ?

Thank you very much!

**Comment by woojeongjin** [comment]
Hi!
1. There is no rules for assigning ids. I just assign ids randomly.
2. Yes makes sense
3. No in our case. We use the same ids for subject and object entities since they are 'same' entities.
4. YAGO dataset has time period if you look at original data.

Thanks!
