### ISSUE TITLE
Running time is too long

### ISSUE THREAD

**Issue by zjwu0522** [INK-USC/RE-Net#52]
I tried to run RE-Net on a Tesla V100, but it takes over 10 hours for one epoch.

Besides, GPU utilization has been very low, I guess it is the problem of dataloader.

I wanna know if anyone has successfully and efficiently implemented this algorithm?

**Comment by woojeongjin** [comment]
Hi! 
Which dataset/version of DGL did you use?

**Comment by MrLiuCC** [comment]
> Hi! Which dataset/version of DGL did you use?

I meet the same problem. When i run train.py,it is too slow.
I  wanna know hou to run ecciciently.
