### ISSUE TITLE
训练时间过长且GPU利用率较低

### ISSUE THREAD

**Issue by maochen136** [INK-USC/RE-Net#53]
数据集每一轮训练时间都很长，并且GPU的利用率较低，请问是否有人和我遇到同样的问题？是不是需要在dataload部分进行修改呢？

**Comment by zjwu0522** [comment]
我也有同样的问题，但我认为不止是dataloader的原因，代码本身的运行效率比较低

**Comment by zhangjinyu19980915** [comment]
> 



> 我也有同样的问题，但我认为不止是dataloader的原因，代码本身的运行效率比较低

你好！我在运行此代码时也发现了同样的问题，请问一下有没有加速的办法。如果可以分享方法感激不尽

**Comment by GrayChan04** [comment]
不好意思请问一下你们的代码都能够正常运行吗？我在pretrain的时候遇到了报错

**Comment by MrLiuCC** [comment]
> 数据集每一轮训练时间都很长，并且GPU的利用率较低，请问是否有人和我遇到同样的问题？是不是需要在dataload部分进行修改呢？

请问你找到解决方法了吗？

**Comment by MrLiuCC** [comment]
> > 
> 
> > 我也有同样的问题，但我认为不止是dataloader的原因，代码本身的运行效率比较低
> 
> 你好！我在运行此代码时也发现了同样的问题，请问一下有没有加速的办法。如果可以分享方法感激不尽

你好！请问你找到加速训练的方法了吗？
