### ISSUE TITLE
Excuse me, where is the code of TTransE?

### ISSUE THREAD

**Issue by GrayChan04** [INK-USC/RE-Net#56]
I'd like to learn how to implement it but unfortunately I can not find the source code in _baseline_ or anything else
Can you offer me the code? My e-mail address is graychan@126.com
If I can receive your reply, I will be quite happy

**Comment by woojeongjin** [comment]
Hi!
Baselines are in https://github.com/INK-USC/RE-Net/tree/master/baselines
Thanks!
